# Generated by Django 2.1 on 2018-11-02 10:06

from django.db import migrations
import filebrowser.fields


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0002_newsletter_lead'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='image',
            field=filebrowser.fields.FileBrowseField(blank=True, max_length=100, null=True, verbose_name='Image'),
        ),
    ]
