# Generated by Django 2.0 on 2018-11-02 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0003_newsletter_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='text',
            field=models.TextField(blank=True, verbose_name='text'),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='lead',
            field=models.CharField(max_length=100, verbose_name='Lead'),
        ),
    ]
