# Generated by Django 2.0 on 2018-11-02 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0005_achievement'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='achievement',
            options={'ordering': ('order',)},
        ),
        migrations.RemoveField(
            model_name='achievement',
            name='date',
        ),
        migrations.AddField(
            model_name='achievement',
            name='order',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
