# Generated by Django 2.0 on 2018-11-02 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0007_auto_20181102_1537'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='achievement',
            options={},
        ),
        migrations.AlterModelOptions(
            name='achievementnewslettter',
            options={'ordering': ('order',), 'verbose_name': 'Achievement newsletter', 'verbose_name_plural': 'Achievements newsletter'},
        ),
        migrations.RemoveField(
            model_name='achievement',
            name='order',
        ),
        migrations.AddField(
            model_name='achievementnewslettter',
            name='order',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
