# Generated by Django 2.0 on 2018-11-02 14:05

from django.db import migrations, models
import filebrowser.fields


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0008_auto_20181102_1540'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140, verbose_name='Title')),
                ('text', models.TextField(blank=True, verbose_name='text')),
                ('image', filebrowser.fields.FileBrowseField(blank=True, max_length=100, null=True, verbose_name='Image')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='achievement',
            options={'verbose_name': 'Achievement', 'verbose_name_plural': 'Achievements'},
        ),
    ]
