# Generated by Django 2.0 on 2018-11-02 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0010_event_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventNewslettter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsletter.Event')),
                ('newsletter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='newsletter_event', to='newsletter.Newsletter')),
            ],
            options={
                'verbose_name': 'Event newsletter',
                'verbose_name_plural': 'Events newsletter',
                'ordering': ('order',),
            },
        ),
    ]
