# Generated by Django 2.0 on 2018-11-02 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0011_eventnewslettter'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='slug',
            field=models.SlugField(default='test'),
            preserve_default=False,
        ),
    ]
