# Generated by Django 2.0 on 2018-11-05 10:01

from django.db import migrations, models
import filebrowser.fields


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0015_auto_20181105_1133'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=140, verbose_name='Last Name')),
                ('photo', filebrowser.fields.FileBrowseField(blank=True, max_length=100, null=True, verbose_name='Photo')),
                ('profile_url', models.URLField(blank=True, verbose_name='UCern Profile URL')),
            ],
        ),
    ]
