# Generated by Django 2.0 on 2018-11-05 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0016_member'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberNewsletter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField()),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsletter.Member')),
            ],
            options={
                'verbose_name': 'Member newsletter',
                'verbose_name_plural': 'Members newsletter',
                'ordering': ('order',),
            },
        ),
        migrations.AddField(
            model_name='newsletter',
            name='thank_you_text',
            field=models.TextField(blank=True, verbose_name='Special thank you message'),
        ),
        migrations.AddField(
            model_name='membernewsletter',
            name='newsletter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='newsletter_member', to='newsletter.Newsletter'),
        ),
        migrations.AddField(
            model_name='member',
            name='newsletters',
            field=models.ManyToManyField(blank=True, null=True, related_name='member', through='newsletter.MemberNewsletter', to='newsletter.Newsletter', verbose_name='Newsletter'),
        ),
    ]
