# Generated by Django 2.0 on 2018-11-06 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0017_auto_20181105_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='flag_image',
            field=models.URLField(blank=True, help_text='Paste the url of the image', verbose_name='Flag image'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='image',
            field=models.URLField(blank=True, default='', help_text='Paste the url of the image', verbose_name='Image'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.URLField(blank=True, default='', help_text='Paste the url of the image', verbose_name='Image'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='member',
            name='photo',
            field=models.URLField(blank=True, default='', help_text='Paste the url of the image', verbose_name='Photo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='image',
            field=models.URLField(blank=True, default='', help_text='Paste the url of the image', verbose_name='Image'),
            preserve_default=False,
        ),
    ]
