# Generated by Django 2.0 on 2018-11-20 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0019_auto_20181120_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalthought',
            name='thoughts',
            field=models.ManyToManyField(blank=True, null=True, related_name='finalthoughts', through='newsletter.FinalThoughtNewsletter', to='newsletter.FinalThought', verbose_name='Newsletter'),
        ),
    ]
