# Generated by Django 2.0 on 2018-11-20 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0020_auto_20181120_1609'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finalthought',
            name='thoughts',
        ),
        migrations.AddField(
            model_name='finalthought',
            name='newsletters',
            field=models.ManyToManyField(blank=True, null=True, related_name='final_thought', through='newsletter.FinalThoughtNewsletter', to='newsletter.Newsletter', verbose_name='Newsletter'),
        ),
    ]
